### ISSUE TITLE
登陆后会卡住

### ISSUE THREAD

**Issue by 14790897** [ukuq/seer2-server#1]
![image](https://github.com/ukuq/seer2-server/assets/121866954/7afe7142-c6ba-4945-ba3e-5c72f74da2a1)

"C:\Program Files\Java\jdk-17\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.3\lib\idea_rt.jar=53343:C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.3\bin" -Dfile.encoding=UTF-8 -classpath C:\git-program\seer2-server\out\production\seer2-server seer2.MainFrame
等待连接1201---
等待连接 电信 5001 ---
等待连接 网通 5000 ---
cmdId:[0-该条命令定义不存在], length:1819242556, uid:1768303993, sequenceIndex:1915577708, statusCode:1702195557
login-c:1:[3c, 70, 6f, 6c, 69, 63, 79, 2d, 66, 69, 6c, 65, 2d, 72, 65, 71, 75, 65, 73, 74, 2f, 3e, 00]

cmdId:[0-该条命令定义不存在], length:1836597052, uid:1936876918, sequenceIndex:1030647657, statusCode:808333602
login-s:2:[3c, 3f, 78, 6d, 6c, 20, 76, 65, 72, 73, 69, 6f, 6e, 3d, 22, 31, 2e, 30, 22, 3f, 3e, 3c, 21, 44, 4f, 43, 54, 59, 50, 45, 20, 63, 72, 6f, 73, 73, 2d, 64, 6f, 6d, 61, 69, 6e, 2d, 70, 6f, 6c, 69, 63, 79, 3e, 3c, 63, 72, 6f, 73, 73, 2d, 64, 6f, 6d, 61, 69, 6e, 2d, 70, 6f, 6c, 69, 63, 79, 3e, 3c, 61, 6c, 6c, 6f, 77, 2d, 61, 63, 63, 65, 73, 73, 2d, 66, 72, 6f, 6d, 20, 64, 6f, 6d, 61, 69, 6e, 3d, 22, 2a, 22, 20, 74, 6f, 2d, 70, 6f, 72, 74, 73, 3d, 22, 2a, 22, 20, 2f, 3e, 3c, 2f, 63, 72, 6f, 73, 73, 2d, 64, 6f, 6d, 61, 69, 6e, 2d, 70, 6f, 6c, 69, 63, 79, 3e, 00]

cmdId:[103-Login], length:212, uid:0, sequenceIndex:0, statusCode:2901
login-c:3:[d4, 00, 00, 00, 67, 00, 00, 00, 00, 00, 00, 00, 00, 00, 55, 0b, 00, 00, 31, 38, 32, 32, 31, 35, 32, 31, 35, 37, 36, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 63, 62, 39, 39, 33, 35, 61, 38, 32, 62, 34, 64, 37, 37, 38, 36, 66, 33, 37, 66, 32, 66, 62, 32, 32, 63, 32, 63, 38, 39, 30, 35, 41, 00, 00, 00, 0a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 30, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]

cmdId:[103-Login], length:42, uid:957282332, sequenceIndex:0, statusCode:0
login-s:4:[2a, 00, 00, 00, 67, 00, 1c, f8, 0e, 39, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 6b, cf, d6, 8f, 0e, 6d, 0d, 73, 8b, 8c, e5, e9, f2, 90, ee, 5f, 01, 00, 00, 00]
MainServerLoginInfo{resultFlag=0, account='null', password='null', session=[107, -49, -42, -113, 14, 109, 13, 115, -117, -116, -27, -23, -14, -112, -18, 95], hasRole=true, verifyImgId=null, verifyImgDataSize=0, verifyImgData=null, lastLoginIP='null', lastLoginTime=0, lastLoginCity='null', curLoginCity='null'}

cmdId:[111-Check role exists in data base], length:34, uid:957282332, sequenceIndex:0, statusCode:2382
login-c:5:[22, 00, 00, 00, 6f, 00, 1c, f8, 0e, 39, 00, 00, 00, 00, 4e, 09, 00, 00, 6b, cf, d6, 8f, 0e, 6d, 0d, 73, 8b, 8c, e5, e9, f2, 90, ee, 5f]

cmdId:[111-Check role exists in data base], length:22, uid:957282332, sequenceIndex:0, statusCode:0
login-s:6:[16, 00, 00, 00, 6f, 00, 1c, f8, 0e, 39, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00]

cmdId:[105-Get recommend server list], length:38, uid:957282332, sequenceIndex:0, statusCode:2447
login-c:7:[26, 00, 00, 00, 69, 00, 1c, f8, 0e, 39, 00, 00, 00, 00, 8f, 09, 00, 00, 6b, cf, d6, 8f, 0e, 6d, 0d, 73, 8b, 8c, e5, e9, f2, 90, ee, 5f, 41, 00, 00, 00]

cmdId:[105-Get recommend server list], length:295, uid:957282332, sequenceIndex:0, statusCode:0
login-s:8:[27, 01, 00, 00, 69, 00, 1c, f8, 0e, 39, 00, 00, 00, 00, 00, 00, 00, 00, 3c, 00, 00, 00, 0a, 00, 00, 00, 34, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, fe, 04, 00, 00, 00, 00, 00, 01, 33, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, fd, 04, 00, 00, 00, 00, 00, 01, 35, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, ff, 04, 00, 00, 00, 00, 00, 01, 36, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, 00, 05, 00, 00, 00, 00, 00, 01, 37, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, 01, 05, 00, 00, 00, 00, 00, 01, 38, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, 02, 05, 00, 00, 00, 00, 00, 01, 02, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, b2, 04, 00, 00, 00, 00, 00, 00, 03, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, b3, 04, 00, 00, 00, 00, 00, 00, 0b, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, bb, 04, 00, 00, 00, 00, 00, 00, 0f, 00, 31, 31, 38, 2e, 38, 39, 2e, 31, 34, 39, 2e, 31, 38, 39, 00, dd, bf, 04, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00]
0
0
check: 0
OnlineServerListInfo{isNewPlayer=1, serverTotalCount=60, serverInfos=[
ServerInfo{serverId=52, serverIp='118.89.149.189 �', serverPort=1278, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=51, serverIp='118.89.149.189 �', serverPort=1277, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=53, serverIp='118.89.149.189 �', serverPort=1279, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=54, serverIp='118.89.149.189 �', serverPort=1280, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=55, serverIp='118.89.149.189 �', serverPort=1281, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=56, serverIp='118.89.149.189 �', serverPort=1282, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=2, serverIp='118.89.149.189 �', serverPort=1202, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=3, serverIp='118.89.149.189 �', serverPort=1203, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=11, serverIp='118.89.149.189 �', serverPort=1211, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=15, serverIp='118.89.149.189 �', serverPort=1215, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}]}

已退出 ----
lid:0
cmdId:[1001-Login to online server], length:102, uid:957282332, sequenceIndex:165, statusCode:3290
proxy-c:9:[0a, 00, 00, 00, 6b, cf, d6, 8f, 0e, 6d, 0d, 73, 8b, 8c, e5, e9, f2, 90, ee, 5f, 30, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
[67, 00, 00, 00, e9, 03, 03, 2d, 33, 8c, 0a, b8, ec, 6b, ee, 37, 4d, 4e, a6, 6a, ed, cb, 0f, 69, 57, d4, 3d, 0c, 00, cd, 82, fa, 1f, 90, 11, 50, 34, 96, e6, cd, 6f, 84, 8e, 2e, ec, ad, ad, ac, ec, 6b, ae, ac, 4c, 4e, e6, 6b, ed, cb, 6f, 84, 8e, 2e, ec, ad, ad, ac, ec, 6b, ae, ac, 4c, 4e, e6, 6b, ed, cb, 6f, 84, 8e, 2e, ec, ad, ad, ac, ec, 6b, ae, ac, 4c, 4e, e6, 6b, ed, cb, 6f, 84, 8e, 2e, ec, ad, ad, ac, 0c]
连接中断---
java.net.UnknownHostException: 118.89.149.189 �
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at seer2.MainFrame$ProxyHandler.run(MainFrame.java:281)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 14790897** [comment]
fiddler端口设置的是5000

**Comment by 14790897** [comment]
按照readme设置成127.0.0.1:5002是没有反应的

**Comment by ukuq** [comment]
看着像是java.net.UnknownHostException: 118.89.149.189 �这里的问题。
可以试试将代理地址做一下手动trim处理，可以参考这里的写法：https://github.com/arcadia-star/seer2-next-message/blob/63bf976386e8462153dc5e22027190873e3ebd27/src/main.rs#L74
去掉\0字符后面的所有字符

**Comment by 14790897** [comment]
修改了281行的代码 socket2 = new Socket(serverInfo.getServerIp().trim().replace("\0", ""),1218);
进来了，但好像没什么变化

**Comment by 14790897** [comment]
ServerInfo{serverId=18, serverIp='118.89.149.189 �', serverPort=1218, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=19, serverIp='118.89.149.189 �', serverPort=1219, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=20, serverIp='118.89.149.189 �', serverPort=1220, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=22, serverIp='118.89.149.189 �', serverPort=1235, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}]}

已退出 ----
现在命令行显示这些内容

**Comment by ukuq** [comment]
或者你把ip写死吧：118.89.149.189
服务器游戏ip固定是这个

**Comment by 14790897** [comment]
# 在serverinfo.java里写好了：
```
    public ServerInfo(ByteArray param1){
        if(param1!=null){
            this.serverId = param1.readUnsignedShort();
            this.serverIp = param1.readUTFBytes(16);
            this.serverIp = "118.89.149.189";
            this.serverPort = param1.readUnsignedShort();
            this.userCount = param1.readUnsignedInt();
            this.friendCount = param1.readUnsignedByte();
            this.isNewSvr = param1.readUnsignedByte();
        }
    }
```
# 命令行输出：
ServerInfo{serverId=55, serverIp='118.89.149.189', serverPort=1281, userCount=0, friendCount=0, isNewSvr=1, isRecommendSvr=0}, 
ServerInfo{serverId=48, serverIp='118.89.149.189', serverPort=1274, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=22, serverIp='118.89.149.189', serverPort=1235, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=20, serverIp='118.89.149.189', serverPort=1220, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}, 
ServerInfo{serverId=19, serverIp='118.89.149.189', serverPort=1219, userCount=0, friendCount=0, isNewSvr=0, isRecommendSvr=0}]}

已退出 ----


# 游玩体验
没有变化

**Comment by ukuq** [comment]
socket2 = new Socket(serverInfo.getServerIp(),1218);
改成 
socket2 = new Socket(serverInfo.getServerIp(),serverInfo.getServerPort());
或者
socket2 = new Socket("118.89.149.189",serverInfo.getServerPort());

**Comment by 14790897** [comment]
还是类似的输出，游戏没有变化，不会就我一个人尝试自己部署吧？

**Comment by ukuq** [comment]
MainFrame 那个是代理服务器，Seer2App 可能才是你需要的

**Comment by 14790897** [comment]
不知不觉玩了一小时，比grasscutter好玩

**Comment by ukuq** [comment]
> 不知不觉玩了一小时，比grasscutter好玩

夸张了，里面没啥内容，对战啥的都没做，也就只能跑跑地图了
